const test = require('node:test');
const assert = require('node:assert/strict');
const { JSDOM } = require('jsdom');
const fs = require('node:fs');
const path = require('node:path');
const read = name => fs.readFileSync(path.join(__dirname, '..', name), 'utf8');

test('tracker renders quarterly and multi-year benefits consistently, records edits, refreshes after sync', async () => {
  const dom = new JSDOM(read('pages/tracker.html'), { url: 'https://cardmax.test/pages/tracker.html', runScripts: 'outside-only' });
  const w = dom.window;
  w.localStorage.setItem('cardmax_user_cards', '["amex-platinum","capital-one-venture-x"]');
  w.CardMaxAuth = { autoSync() { w.CardMaxStorage.captureChanges(); } };
  w.CardMaxSave = { renderSaveRestoreUI() {} };
  w.eval(['data/cards.js', 'js/card-model.js', 'js/storage.js', 'js/benefit-periods.js', 'js/tracker.js'].map(read).join('\n')); 
  await new Promise(resolve => w.document.addEventListener('DOMContentLoaded', resolve));
  const quarterly = w.document.querySelector('#quarterly-benefits-container');
  assert.match(quarterly.textContent, /Resy/);
  const pointRow = [...w.document.querySelectorAll('#by-card-container .benefit-item')].find(node => /Anniversary Bonus/.test(node.textContent));
  assert.match(pointRow.textContent, /10,000 pts/);
  assert.doesNotMatch(pointRow.textContent, /\$10,000/);
  const globalEntries = [...w.document.querySelectorAll('[data-benefit]')].filter(input => input.dataset.benefit.includes('capital-one-venture-x|global-entry'));
  assert.equal(globalEntries.length, 2);
  assert.equal(globalEntries[0].dataset.benefit, globalEntries[1].dataset.benefit);
  globalEntries[0].dispatchEvent(new w.Event('change', { bubbles: true }));
  const benefits = JSON.parse(w.localStorage.getItem('cardmax_tracked_benefits'));
  assert.equal(benefits[globalEntries[0].dataset.benefit].completed, true);
  const cashInput = w.document.querySelector('[data-cash-used]');
  assert.ok(cashInput);
  cashInput.value = '40';
  cashInput.dispatchEvent(new w.Event('input', { bubbles: true }));
  w.switchView('frequency');
  assert.equal(JSON.parse(w.localStorage.getItem('cardmax_tracked_benefits'))[cashInput.dataset.cashUsed].cashValue, 40);
  cashInput.dispatchEvent(new w.Event('change', { bubbles: true }));
  assert.equal(w.document.querySelector('[data-cash-used]').value, '40');
  w.CardMaxStorage.restore({ ...w.CardMaxStorage.readSnapshot(), cards: [] });
  assert.match(w.document.getElementById('by-card-container').textContent, /No cards selected/);
  dom.window.close();
});

test('fixed-period date edits reject a previous period and explain the allowed range', async () => {
  const dom = new JSDOM(read('pages/tracker.html'), { url: 'https://cardmax.test/pages/tracker.html', runScripts: 'outside-only' });
  const w = dom.window;
  w.localStorage.setItem('cardmax_user_cards', '["amex-platinum"]');
  w.CardMaxAuth = { autoSync() { w.CardMaxStorage.captureChanges(); } };
  w.CardMaxSave = { renderSaveRestoreUI() {} };
  w.eval(['data/cards.js', 'js/card-model.js', 'js/storage.js', 'js/benefit-periods.js', 'js/tracker.js'].map(read).join('\n'));
  await new Promise(resolve => w.document.addEventListener('DOMContentLoaded', resolve));
  const checkbox = [...w.document.querySelectorAll('#by-card-container [data-benefit]')].find(input => input.dataset.benefit.includes('|uber-credit|'));
  const key = checkbox.dataset.benefit;
  checkbox.dispatchEvent(new w.Event('change', { bubbles: true }));
  const input = [...w.document.querySelectorAll('#by-card-container [data-used-date]')].find(input => input.dataset.usedDate === key);
  const before = JSON.parse(w.localStorage.getItem('cardmax_tracked_benefits'))[key];
  const date = w.CardMaxPeriods.parseDate(before.periodStart); date.setDate(date.getDate() - 1);
  input.value = w.CardMaxPeriods.dateKey(date);
  input.dispatchEvent(new w.Event('input', { bubbles: true }));
  assert.equal(JSON.parse(w.localStorage.getItem('cardmax_tracked_benefits'))[key].usedAt, before.usedAt);
  input.dispatchEvent(new w.Event('change', { bubbles: true }));
  assert.equal(input.value, before.usedAt);
  assert.equal(input.getAttribute('aria-invalid'), 'true');
  assert.match(input.closest('.benefit-item').querySelector('[data-date-error]').textContent, /within this benefit period/);
  input.value = before.periodStart;
  input.dispatchEvent(new w.Event('change', { bubbles: true }));
  assert.equal(JSON.parse(w.localStorage.getItem('cardmax_tracked_benefits'))[key].usedAt, before.periodStart);
  dom.window.close();
});

test('switching views immediately reflects partial cash edits in inputs and current allowances', async () => {
  const dom = new JSDOM(read('pages/tracker.html'), { url: 'https://cardmax.test/pages/tracker.html', runScripts: 'outside-only' });
  const w = dom.window;
  w.localStorage.setItem('cardmax_user_cards', '["amex-platinum"]');
  w.CardMaxAuth = { autoSync() { w.CardMaxStorage.captureChanges(); } };
  w.CardMaxSave = { renderSaveRestoreUI() {} };
  w.eval(['data/cards.js', 'js/card-model.js', 'js/storage.js', 'js/benefit-periods.js', 'js/tracker.js'].map(read).join('\n'));
  await new Promise(resolve => w.document.addEventListener('DOMContentLoaded', resolve));
  const resy = [...w.document.querySelectorAll('#by-card-container [data-benefit]')].find(input => input.dataset.benefit.includes('|resy-credit|'));
  const key = resy.dataset.benefit;
  resy.dispatchEvent(new w.Event('change', { bubbles: true }));
  const cash = [...w.document.querySelectorAll('#by-card-container [data-cash-used]')].find(input => input.dataset.cashUsed === key);
  assert.equal(cash.value, '100');
  cash.value = '40';
  cash.dispatchEvent(new w.Event('input', { bubbles: true }));
  // No change event or reload: the newly shown view must use the live record.
  w.switchView('frequency');
  const quarterly = w.document.getElementById('quarterly-benefits-container');
  assert.equal([...quarterly.querySelectorAll('[data-cash-used]')].find(input => input.dataset.cashUsed === key).value, '40');
  assert.match(quarterly.querySelector('.tracker-progress').textContent, /\$40\.00\s*\/\s*\$175\.00/);
  assert.equal(w.document.getElementById('annual-value').textContent, '$40.00');
  w.switchView('card');
  assert.equal([...w.document.querySelectorAll('#by-card-container [data-cash-used]')].find(input => input.dataset.cashUsed === key).value, '40');
  assert.equal(JSON.parse(w.localStorage.getItem('cardmax_tracked_benefits'))[key].cashValue, 40);
  dom.window.close();
});
