// Reviewed JSON is the source of truth; cards.js is the browser-compatible artifact.
const fs = require('node:fs');
const path = require('node:path');
const { validateCatalog } = require('./validate-catalog');
const root = path.resolve(__dirname, '..');
function compileCatalog({ check = false } = {}) {
  const directory = path.join(root, 'data/reviewed');
  const names = ['amex-cards.json', 'banks-cards.json', 'chase-cards.json', 'other-cards.json'];
  const cards = names.flatMap(name => JSON.parse(fs.readFileSync(path.join(directory, name), 'utf8')));
  validateCatalog(cards);
  const manifest = require('../docs/catalog-id-manifest.json');
  const order = new Map(manifest.map((card, index) => [card.id, index]));
  cards.sort((a, b) => (order.get(a.id) ?? 1000) - (order.get(b.id) ?? 1000) || a.name.localeCompare(b.name, 'en'));
  for (const published of manifest) {
    const card = cards.find(card => card.id === published.id);
    if (!card) throw new Error(`Published card ID disappeared: ${published.id}`);
    for (const [active, retired] of [['credits', 'retiredBenefits'], ['perks', 'retiredPerks']]) {
      const ids = new Set([...(card[active] || []), ...(card[retired] || [])].map(item => item.id));
      for (const id of published[active]) if (!ids.has(id)) throw new Error(`Published benefit ID disappeared: ${card.id}/${id}`);
    }
  }
  const output = '// Generated by npm run catalog from data/reviewed/*.json. Do not edit directly.\n' +
    '// amount is an annual cap or an explicit non-cash quantity; period amounts are separate.\n' +
    `const CARDS_DATABASE = ${JSON.stringify(cards, null, 2)};\n` +
    'const CARD_ID_ALIASES = Object.freeze({});\n' +
    "if (typeof module !== 'undefined' && module.exports) module.exports = CARDS_DATABASE;\n";
  const destination = path.join(root, 'data/cards.js');
  if (check) {
    if (fs.readFileSync(destination, 'utf8') !== output) throw new Error('Generated catalog is stale. Run npm run catalog.');
  } else fs.writeFileSync(destination, output);
  return cards;
}
module.exports = { compileCatalog };
if (require.main === module) console.log(`${compileCatalog({ check: process.argv.includes('--check') }).length} cards compiled and checked.`);
